Fix Script error, uniforms for Ai
XEngima/Intrusion pull request #8
Opened 2019-05-05 11:13 UTC by joseffallman

+ Helicrew uniforms.
+ Infantry will have theirs uniform when entering a free vehicle.

2019-05-06 05:14 UTC, XEngima requested changes

2019-05-06 05:14 UTC, XEngima commented on Client/Classes/Recievers/ClientEventReciever.sqx
> +		public static method OnUnitEnteredVehicle("_unit" as Object, "_role" as String, "_vehicle" as Object, "_turret" as Array)
Denna ska ta emot _role av typen VehicleRole.

2019-05-06 05:14 UTC, XEngima commented on Client/Classes/Recievers/ClientEventReciever.sqx
> -				[_unit, _role, _vehicle] call ClientSquadHandler.SetUniform;
Använd VehicleRoleMeta.ToString för att konvertera en _role av typen VehicleRole till String.

2019-05-06 05:14 UTC, XEngima commented on Common/Classes/Configs/UniformConfig.sqx
> +				_mUniformInfos pushBack [west, "U_B_HeliPilotCoveralls", "H_PilotHelmetHeli_B", ProfessionType.ReconChopper, VehicleRole.Turret] new UniformInfo;
Aha, now I got why these are extra indented... :)

2019-05-06 05:14 UTC, XEngima commented on Common/Classes/Handlers/CommonSquadHandler.sqx
> +		private static fields ["_mUniformConfig" as UniformConfig];
New classes are not allowed to be static. Instead it should be instantiated and put as a property into class IntrusionCommon.

Reason to avoid static classes is that they are not interfacable and thus not testable.

2019-05-06 05:14 UTC, XEngima commented on Common/Classes/Handlers/CommonSquadHandler.sqx
> +		public constructor("_uniformConfig" as UniformConfig) {
Having an instance constructor in a class meant to be static may lead to strange behavior. If a class is intended to be static, use a static Init() method instead. However, static classes should be rare, and not to be used in this case.

2019-05-06 05:14 UTC, XEngima commented on Common/Classes/Handlers/CommonSquadHandler.sqx
> +			if (
Add a comment above this if that explains it in words. It is too hard to understand the logic being evaluated and its purpose.

2019-05-06 05:14 UTC, XEngima commented on Common/Enums/VehicleRole.sqx
> +		Turret = 5
Not sure if this is correct. A person in a turret, does it not always have the role of a gunner? Let's not confuse the vehicle role with vehicle position. Do we need a new VehiclePosition enum?

2019-05-06 05:14 UTC, XEngima commented on Intrusion.tproj
> -          <ProjectNodeViewModel xsi:type="ProjectFileNodeViewModel" Name="InitCommon.sqx" IsExpanded="false" FileName="Common\InitCommon.sqx">
This is a dilemma with TypeSqf. To keep clean from these kinds of lines, always close TypeSqf when doing commit. Or as an alternative select the root node of the projekt, right click and select collapse all sub nodes.

2019-05-06 05:14 UTC, XEngima commented on Server/Classes/Handlers/ServerEventHandlers.sqx
> -				["ClientEventReciever.OnUnitEnteredVehicle", [_unit, [_role] call VehicleRoleMeta.ToVehicleRole, _vehicle, _turret]] call Remote.Invoke;
Personally I think we should check if role is "TURRET" and in that case convert it to "GUNNER". Alternatively we should rename the VehicleRole enum to VehiclePosition. Just to keep the integrity in the semantics.

2019-05-07 18:15 UTC, joseffallman commented on Common/Classes/Handlers/CommonSquadHandler.sqx
> +		private static fields ["_mUniformConfig" as UniformConfig];
Changed this to a UniformHandler, added as a property in IntrusionCommon.
Added static fields to ClientEventReciever and ServerEventReciever to hold the UniformHandler and make it accessible in those classes. Is this approach following the code guidelines?

2019-05-07 18:27 UTC, XEngima commented
Yes. But it is also ok to use the global (gCommon) in the event recievers.

Sent from ProtonMail Mobile

On tis, maj 7, 2019 at 20:15, joseffallman <notifications@github.com> wrote:

> @joseffallman commented on this pull request.
>
> ---------------------------------------------------------------
>
> In [Common/Classes/Handlers/CommonSquadHandler.sqx](https://github.com/XEngima/Intrusion/pull/8#discussion_r281763347):
>
>> @@ -0,0 +1,80 @@
> +/*
> + * Name:	CommonSquadHandler
> + * Date:	2019-05-05
> + * Version: 1.0
> + * Author:  Josef
> + *
> + * Description:
> + * Common squad handlers related methods
> + */
> +namespace Intrusion.Common
> +{
> +	public class CommonSquadHandler
> +	{
> +		private static fields ["_mUniformConfig" as UniformConfig];
>
> Changed this to a UniformHandler, added as a property in IntrusionCommon.
> Added static fields to ClientEventReciever and ServerEventReciever to hold the UniformHandler and make it accessible in those classes. Is this approach following the code guidelines?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, [view it on GitHub](https://github.com/XEngima/Intrusion/pull/8#discussion_r281763347), or [mute the thread](https://github.com/notifications/unsubscribe-auth/AHDZRI4XGARUCUWWZ7VVCQLPUHBNNANCNFSM4HK3AAOQ).

2019-05-07 19:58 UTC, merged